#!/usr/bin/env bash
# This script creates a file containing its PID, displays messages indefinitely, and 
# terminates itself when receiving a SIGQUIT or SIGTERM signal, also it delete the created PID file

echo "$$" > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true; do
      echo "To infinity and beyond"
      sleep 2
done
